name: run-crawler
on:
  workflow_dispatch:
  schedule:
    # At minute 0 past every 4th hour from 9 through 17
    # see https://crontab.guru/#0_9-18/3_*_*_*
    - cron: 0 9-17/4 * * *
jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: yarn install
      - run: yarn start
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_X509_CERT_URL: ${{ secrets.CLIENT_X509_CERT_URL }}
